[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_claim_contract = "Ds8x3BtoYpSKvKPt6g2JU8UtAsYcaLhDsbFycwdAM81H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
